# Generated by Django 3.0.8 on 2020-07-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='your_name',
        ),
    ]
