# Generated by Django 3.1.2 on 2020-10-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='short_url',
            field=models.TextField(default='https://diamondnepal.com/s/', null=True),
        ),
    ]
